# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efedc2c0da797551e9de831faccd9228db18792933cabdc7f5fc29994a0ac17f839258358c3de42fa66d892d3ef4e0b9c9c701b0634430833b5262931ebb2646

test:
  secret_key_base: fc6a37e1a623fd5e8c90cf15619aa73d3ca23231048108e661687a21af6f090c32e0df4af52e340327058c04cbf9d168dce597940cda5306d7616bebf06d70ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
